### PR TITLE
pad image at inference time, remove resize

### PR DESCRIPTION
**Pull request by desi-ivanova**
## Changes

At inference time, pad the image instead of doing an interpolation-based resize, which gives poor results (e.g. on PSNR) when the input image heigh and/or width is not exactly divisible by the downsampling factor (`=2^{number of downsampling layers}`).

### CODE REVIEW

**Review by mmuckley — APPROVED** [review]
LGTM. Thanks for finding this!

**Comment by mmuckley** [comment]
@desi-ivanova could you fix the failed tests? Then I can merge.

**Comment by desi-ivanova** [comment]
@mmuckley let me know if there's anything blocking the merge

**Comment by mmuckley** [comment]
@desi-ivanova looks good!

**Pull request merged**
