### PR TITLE
fix the bug of using optical_flow_to_color in train.py

### PR DESCRIPTION
**Pull request by N1ghtstalker2022**
Closes #

## Changes

Change the import of optical_flow_to_color function from `import _optical_flow_to_color` to `from neuralcompression.functional import optical_flow_to_color`.

Change the function call `_optical_flow_to_color.optical_flow_to_color` to `optical_flow_to_color`

### CODE REVIEW

**Comment by mmuckley** [comment]
Hello @N1ghtstalker2022 could you run `black` on this PR so that it passes the tests?

**Comment by N1ghtstalker2022** [comment]
> 

OK. I'll do that.

**Comment by N1ghtstalker2022** [comment]
> Hello @N1ghtstalker2022 could you run `black` on this PR so that it passes the tests?

The black test can be passed on my machine. It should works now.

**Comment by N1ghtstalker2022** [comment]
I don't know why it did not pass the test. The code can pass the test on my linux machine. 
8792b5931187d1bf338e088f9f099c33

**Comment by mmuckley** [comment]
Hello @N1ghtstalker2022, it's just a different test, this one for `isort`. You can see all the tests we run [here](https://github.com/facebookresearch/NeuralCompression/blob/2ead7b4c5e63135537ae27facf2c8c358ce98c57/.github/workflows/build-and-test.yml#L73-L81) so we don't get hit with this again.

**Comment by N1ghtstalker2022** [comment]
> Hello @N1ghtstalker2022, it's just a different test, this one for `isort`. You can see all the tests we run [here](https://github.com/facebookresearch/NeuralCompression/blob/2ead7b4c5e63135537ae27facf2c8c358ce98c57/.github/workflows/build-and-test.yml#L73-L81) so we don't get hit with this again.

I've tested it again. Now it should be fine.

**Comment by mmuckley** [comment]
@N1ghtstalker2022 yes thanks so much! Sorry, was busy with some other things.

**Pull request merged**
